name: benchmark
on: workflow_dispatch
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: checkout Easy-Graph
        uses: actions/checkout@v3
        with:
          repository: easy-graph/Easy-Graph
          # ref: '6dade6c6'
          # path: Easy-Graph
      - name: b
        env:
          python_version: '3.9'
          boost_version: "1.79.0"
        run: |          
          python_version_abbr=${python_version//./}
          boost_version_alias=boost_${boost_version//./_}
          sudo apt-get update
          sudo apt-get install gcc -y
          sudo apt-get install g++ -y
          wget https://boostorg.jfrog.io/artifactory/main/release/${boost_version}/source/${boost_version_alias}.tar.gz
          tar -xf ${boost_version_alias}.tar.gz
          cd ${boost_version_alias}
          ./bootstrap.sh --with-python=python
          sudo ./b2 cxxflags="-fPIC" install --with-python
          cd ${{ github.workspace }}
          
          sudo ln -s /usr/local/lib/libboost_python${python_version_abbr}.a /usr/local/lib/libboost_python.a
          pip install pytest
          pip install Pillow
          pip install kiwisolver
          pip install gensim
          pip install lxml
          python setup.py build_ext -l boost_python -L "/usr/local/lib" -I "/usr/local/include"
          python setup.py install
        


      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: tddschn

      - name: Install dependencies
        run: |
          cd "{{ github.workspace }}"
          pip install -r requirements.txt

      - name: benchmark
        run: |
          cd "{{ github.workspace }}"
          python3 ./bench.py

      