name: benchmark
on: workflow_dispatch
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          git clone https://github.com/easy-graph/Easy-Graph.git
          git -C Easy-Graph checkout 6dade6c6

      - name: benchmark
        run: |
          cd "{{ github.workspace }}"
          python3 ./bench.py

      