name: Benchmark using all datasets
on:
  workflow_dispatch:
    releaseTag:
      required: false
      description: "Release tag for the benchmark results"
      # default: "latest"
      default: "CI"
      type: string
jobs:
  bench_all:
    name: Benchmark using all datasets
    strategy:
      fail-fast: false
      matrix:
        # benchScriptSet: ["stub", "stub-fast", "normal", "large", "coauthorship"]
        benchScriptSet: ["stub", "stub-fast"]
    uses: tddschn/easygraph-bench/.github/workflows/bench.yaml@master
    with:
      benchScriptSet: "${{ matrix.benchScriptSet }}"
      # runs-on
      # python-version
      # timeout
      # cpp-binding-framework
      # releaseTag
      uploadResultsAsArtifact: true

  merge_and_release:
    name: Merge bench results and create release
    runs-on: ubuntu-latest
    needs: bench_all
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Checkout easygraph-bench
        uses: actions/checkout@v3
        with:
          repository: tddschn/easygraph-bench

      - name: Install dependencies for easygraph-bench
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Download result artifacts
        uses: actions/download-artifact@v3
        with:
          path: bench-results

      - name: Check downloaded artifacts
        working-directory: bench-results
        shell: bash
        run: |
          pwd
          ls -lh **/*.csv
          tail -n +1 **/*.csv

      - name: Setup tmate session
        # https://github.com/mxschmitt/action-tmate
        # Only on failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          # timeout-minutes: 15
          # By default the tmate session will remain open until the workflow times out. You can specify your own timeout in minutes if you wish to reduce GitHub Actions usage.
          limit-access-to-actor: true
          # Use registered public SSH key(s)
          # By default anybody can connect to the tmate session. You can opt-in to install the public SSH keys that you have registered with your GitHub profile.

          # tmate-server-host: ssh.tmate.io
          # tmate-server-port: 22
          # tmate-server-rsa-fingerprint: SHA256:Hthk2T/M/Ivqfk1YYUn5ijC2Att3+UPzD7Rn72P5VWs
          # tmate-server-ed25519-fingerprint: SHA256:jfttvoypkHiQYUqUCwKeqd9d1fJj/ZiQlFOHVl6E9sI
          # Use your own tmate servers
          # By default the tmate session uses ssh.tmate.io. You can use your own tmate servers. tmate-ssh-server is the server side part of tmate.

          # install-dependencies: false
          # Skip installing tmate
          # By default, tmate and its dependencies are installed in a platform-dependent manner. When using self-hosted agents, this can become unnecessary or can even break. You can skip installing tmate and its dependencies using install-dependencies:

          # Continue a workflow
          # If you want to continue a workflow and you are inside a tmate session, just create a empty file with the name continue either in the root directory or in the project directory by running touch continue or sudo touch /continue.

      - name: Merge results
        run: |
          python3 ./merge_bench_csv.py -c bench-results > all.csv

      - name: Create release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ inputs.releaseTag }}
        run: |
          DATE_STR="$(date +"%Y-%m-%dT%H:%M:%S:%z")"

          CSV_ZIP_FILENAME="bench-results-csv-${DATE_STR}.zip"

          mv all.csv bench-results

          zip -r "${CSV_ZIP_FILENAME}" bench-results

          set +e
          # don't exit on error
          gh release create "${TAG}" --notes "Release from GitHub Actions"
          set -e

          gh release upload "${TAG}" "${CSV_ZIP_FILENAME}"
