---
- name: Clone repositories
  hosts: all
  tasks:
    - name: Clone easygraph-bench
      git:
        repo: https://github.com/tddschn/easygraph-bench
        dest: "{{ ansible_env.HOME }}/easygraph-bench"

    - name: Clone Easy-Graph
      git:
        repo: https://github.com/easy-graph/Easy-Graph
        dest: "{{ ansible_env.HOME }}/Easy-Graph"

    - name: Clone https://github.com/chenyang03/co-authorship-network
      git:
        repo: https://github.com/chenyang03/co-authorship-network
        dest: "{{ ansible_env.HOME }}/co-authorship-network"
