---
- name: Install pipx
  hosts: all
  become: yes
  tasks:
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install pipx
      become_user: "{{ ansible_user }}"
      pip:
        name: pipx
        executable: pip3
