---
- name: Install Conda
  hosts: all
  tasks:
    - name: Download Miniconda installer
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: "{{ ansible_env.HOME }}/miniconda.sh"
        mode: '0755'

    - name: Install Miniconda
      shell: bash ~/miniconda.sh -b -p $HOME/miniconda

    - name: Initialize Conda for zsh
      shell: eval "$(~/miniconda/bin/conda shell.zsh hook)" && conda init zsh
